// Code generated by protoc-gen-corpc.

package pb

import "corpc"

type GroupCacheClient interface {
	Get(args *Request) (*Response, error)
}

type groupCacheClient struct {
	cc *corpc.Client
}

func NewGroupCacheClient(cc *corpc.Client) GroupCacheClient {
	return &groupCacheClient{cc}
}

func (c *groupCacheClient) Get(args *Request) (*Response, error) {
	out := new(Response)
	err := c.cc.Call("GroupCacheService.Get", args, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type GroupCacheServer interface {
	Get(*Request, *Response) error
}

func RegisterGroupCacheServer(s *corpc.Server, srv GroupCacheServer) {
	s.RegisterName("GroupCacheService", srv)
}
